# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b9dfb7ea5f472c4d822080085fc78f48e4765b3ffb49151439666447cc7c6ee988f1013e338eafa76324d2293737515423a34b9c4854fb7c26a56d8c7d7dc1

test:
  secret_key_base: 5a130c881163b5822bfb726d62f4bdf663882d0c9970cd6ec45ce6a193f752c82a912ef918b3d700d92c81132c2810858b0d3490285286de9554bc482ca7a8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
